
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJT2NJbmkxaWV4ckV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMk1UWXhNekEyTXpSYUZ3MHpOakEyTVRNeE16RXhNelJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURFaGNEWTVMU0pYM2QxQm8xT0I4V2RNRS8xRVN0VEJKYUNHc01JZ0JYYmlUREFLaDVFYzRVOVhUMDEKY3lnUlZGQmgrclhVUkxpTHJJM1dYYzNSMDNGUEJSakJvc3JXbnppNERCNERoS2dDR2FkK1F1V2xCZTVDMVB3UAo2Q3hGZ0p2RnYwL2JNWVNxcWxsUWNDcWtUMTBoTmRrdk45V0lEd3dOVDI0c1dZYXRJcDFjcUpSVTZqQ3cvSmNrCndGTGFQTjdJOVlwZi8wVlFENnYvQzdTdk95eDJBRzJzcWczRlQ1MWYrSXFSRUtEZ3k1WFFwNmYyVGxQa3RJeXUKNnpmSG1Ld2ZBcU00TmpNMHZHZHlMQTRHNEVCTENHUE4zRUtQOGprZGs2b09KbVpjM1MvRmxKczJWbzFsWWpMdQpEZzNzSTJZenFITjVnUDB1azdnUXIrWi9sY2R0QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUNnBub2UzWElDM0ZCWjBwVFZ2bkZKMGtLMTdqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlVYaHB4ZmJLVQpnMVBacnp5ZlJRallVanROdFJDOGd2U3Z5R0RPUythMUxHVS9ta2pWcWJwUTJER054U3dVNkt1K21kb3lOM2trCkp5ODBqMEE2ZEttRnUxeWxueUVmZFUvOWlBaFI1dnE5cWdHV1F6NzJkRUdBNThjN3R5ZFMzNHZDV01oRnRkRlIKZVhsZ0FVVHNwRmMzbzlQMTJXeUJTUTVGVEtPNVo3WEtNLzdIa3B1bVhTZytEam1IN21oMUxaUHd5b2owa1B5UgpmZDlBYmR4eGNMWVJnR2FjVFBWaVJRQUpPZEQ3WVNtM1FTVm5GNkZvUUJUWWh4Vnp4MGs5SkpwcCtZUytYMCtKCld3OExzVDMxeVI0V2gxUnFRV1oxR1IrNWhydEc5ZFdFbExSZmFpdVQ1TFZLcWhneTVyS2xDUUZTQi9GQnlkY0UKNVBOdjYyMmFES3VpCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://3fd2069e-9340-418c-bb97-3ff2ef0baa3f.eu-central-2-gw.linodelke.net:443
  name: lke618338

users:
- name: lke618338-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InpYSm5Nc3BXZEpnc041TnduYkpSTzJpRUxkeDFKNjJwUG1VSWZzc3YyWDQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tYzlqengiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZDNkZWJiYTEtNmNiYy00N2JjLTljMTctY2I0Y2RkYmY5OGM1Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.TsqxB1Vso9oZItjSqpFB9d-Cdiiy7OixFF0JUS6tDtGTsI3tJH0u9oetzpPtlgjJDYCZBgSxnOCCcSfvRsUxGQWkkRI2bn8ctYSSqYnXXNMoJ7MDSZgHsvMhBHfChi8esPkv2gcaBQ-DWwfPacDCP47D0s_xNhqty1Lb6UbnTl-cZ4zRsiC54wjhIvnPWVCLuZITAcFzJoHM3AOLZTENNZH7D9yRUWNNJ3hsUsDhOV4I5iyVYC1G04lExsd2wckXOaGd0fqeWuSQVa8JG7z2JyV3P78I2reIK8Mg9VAyyUTKfrWSR6SRnl-9fkBdYF9FI554g8arKxHTNZ-3aZrdEg

contexts:
- context:
    cluster: lke618338
    namespace: default
    user: lke618338-admin
  name: lke618338-ctx

current-context: lke618338-ctx
